### ISSUE TITLE
could you give me your asset

### ISSUE THREAD

**Issue by matrix-yang** [Oceanisher/Unity-DNF#1]

**Comment by Oceanisher** [comment]
> _No description provided._

兄弟，你是要什么资源呀？

**Comment by matrix-yang** [comment]
原来是同胞，我想要是DNF的一些图片和音效背景音乐，就是那种PNG格式的图片，比如人物动作的png,地图的png,技能特效的PNG等等，最近也在学习unity，一起学习。
我看你github中里的资源好像很少，那些我都下载了，如果你有另外的资源且方便，请发我一份，谢谢你。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Oceanisher/Unity-DNF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 下午4:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Oceanisher/Unity-DNF] could you give me your asset (Issue #1)





  
No description provided.
  
兄弟，你是要什么资源呀？

**Comment by Oceanisher** [comment]
哦哦可以可以，我之前也是找别人买的一个Unity工程里带有的资源，我发你qq邮箱一份吧~

**Comment by matrix-yang** [comment]
非常感谢！我会持续关注你的工作，后续我也会去实现DNF的一些场景，到时候可以一起交流，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Oceanisher/Unity-DNF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Oceanisher/Unity-DNF] could you give me your asset (Issue #1)





 
哦哦可以可以，我之前也是找别人买的一个Unity工程里带有的资源，我发你qq邮箱一份吧~

**Comment by Oceanisher** [comment]
与君共勉~
